language: node_js
sudo: required
dist: trusty
node_js: stable
install:
  - npm install -g bower
  - npm install
script:
  - bower install --production
  - npm run -s build
  - bower install
after_success:
  - >-
    test $TRAVIS_TAG &&
    git stash &&
    echo $GITHUB_TOKEN | pulp login &&
    echo y | pulp publish --no-push
